### ISSUE TITLE
Manually turning on the Tuya device will receive both on and off

### ISSUE THREAD

**Issue by seedzhoukang** [TheAgentK/tuya-mqtt#9] opened 2019-01-09 16:36 UTC
![image](https://user-images.githubusercontent.com/45843611/50911283-7c89b800-146a-11e9-8e81-e9d591f3e206.png)
I'll receive on and off at the same time when I manually turn on the Tuya device, and I'll receive off and off when I turn off the device.

I don't know if I'm the only one with this error, here's the code I found the problem with:

```
TuyaDevice.onAll('data', function (data) {
    try {
        debugTuya('Data from device ' + this.type + ' :', data);
        var status = data.dps['1'];
        if (this.type == "lightbulb" && status == undefined) {
            status = true;
        }
        publishStatus(this, bmap(status));
        publishDPS(this, data.dps);
    } catch (e) {
        debugError(e);
    }
});
```
`data` will receive two times the metadata `{"1": true}` and `{"11": 0}`, which will cause the `status` to produce a `undefined`

When I judge `status` as `undefined`, I do nothing to solve the above problems.

**Comment by TheAgentK** [comment] 2019-01-24 16:57
This should be the same error as in error #11

Duplicate of #11

**Closed by TheAgentK** 2019-01-24 16:57 UTC
Labels: bug
